version: '3.8'

services:
  db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest
    networks:
      - base_dev_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SYSTEM=postgres
      - ADMINER_DEFAULT_SERVER=db
    networks:
      - base_dev_network

networks:
  base_dev_network:
